/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -p /home/zyz/works/work/v25/dde-session-shell-snipe/src/global_util/dbus/dbusinterface /home/zyz/works/work/v25/dde-session-shell-snipe/xml/snipe/org.freedesktop.DBus.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSINTERFACE_H
#define DBUSINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <DDBusExtendedAbstractInterface>
#include <QtDBus/QtDBus>


/*
 * Proxy class for interface org.freedesktop.DBus
 */
class __OrgFreedesktopDBusInterfacePrivate;
class __OrgFreedesktopDBusInterface : public DTK_CORE_NAMESPACE::DDBusExtendedAbstractInterface
{
    Q_OBJECT

public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.DBus"; }

public:
    explicit __OrgFreedesktopDBusInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~__OrgFreedesktopDBusInterface();

public Q_SLOTS: // METHODS

Q_SIGNALS: // SIGNALS
    void NameOwnerChanged(const QString &name, const QString &oldOwner, const QString &newOwner);
    // begin property changed signals

public Q_SLOTS:
    void CallQueued(const QString &callName, const QList<QVariant> &args);

private Q_SLOTS:
    void onPendingCallFinished(QDBusPendingCallWatcher *w);

private:
    __OrgFreedesktopDBusInterfacePrivate *d_ptr;
};

namespace org {
  namespace freedesktop {
    typedef ::__OrgFreedesktopDBusInterface DBus;
  }
}
#endif
