/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -p /home/zyz/works/work/v25/dde-session-shell-snipe/src/global_util/dbus/loginedinterface /home/zyz/works/work/v25/dde-session-shell-snipe/xml/snipe/org.deepin.dde.Logined.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "/home/zyz/works/work/v25/dde-session-shell-snipe/src/global_util/dbus/loginedinterface.h"

DCORE_USE_NAMESPACE
/*
 * Implementation of interface class __OrgDeepinDdeLoginedInterface
 */

class __OrgDeepinDdeLoginedInterfacePrivate
{
public:
   __OrgDeepinDdeLoginedInterfacePrivate() = default;

    // begin member variables
    uint LastLogoutUser;
    QString UserList;

public:
    QMap<QString, QDBusPendingCallWatcher *> m_processingCalls;
    QMap<QString, QList<QVariant>> m_waittingCalls;
};

__OrgDeepinDdeLoginedInterface::__OrgDeepinDdeLoginedInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DDBusExtendedAbstractInterface(service, path, staticInterfaceName(), connection, parent)
    , d_ptr(new __OrgDeepinDdeLoginedInterfacePrivate)
{
    connect(this, &__OrgDeepinDdeLoginedInterface::propertyChanged, this, &__OrgDeepinDdeLoginedInterface::onPropertyChanged);

}

__OrgDeepinDdeLoginedInterface::~__OrgDeepinDdeLoginedInterface()
{
    qDeleteAll(d_ptr->m_processingCalls.values());
    delete d_ptr;
}

void __OrgDeepinDdeLoginedInterface::onPropertyChanged(const QString &propName, const QVariant &value)
{
    if (propName == QStringLiteral("LastLogoutUser"))
    {
        const uint &LastLogoutUser = qvariant_cast<uint>(value);
        if (d_ptr->LastLogoutUser != LastLogoutUser)
        {
            d_ptr->LastLogoutUser = LastLogoutUser;
            Q_EMIT LastLogoutUserChanged(d_ptr->LastLogoutUser);
        }
        return;
    }

    if (propName == QStringLiteral("UserList"))
    {
        const QString &UserList = qvariant_cast<QString>(value);
        if (d_ptr->UserList != UserList)
        {
            d_ptr->UserList = UserList;
            Q_EMIT UserListChanged(d_ptr->UserList);
        }
        return;
    }

    qWarning() << "property not handle: " << propName;
    return;
}

uint __OrgDeepinDdeLoginedInterface::lastLogoutUser()
{
    return qvariant_cast<uint>(internalPropGet("LastLogoutUser", &d_ptr->LastLogoutUser));
}

QString __OrgDeepinDdeLoginedInterface::userList()
{
    return qvariant_cast<QString>(internalPropGet("UserList", &d_ptr->UserList));
}

void __OrgDeepinDdeLoginedInterface::CallQueued(const QString &callName, const QList<QVariant> &args)
{
    if (d_ptr->m_waittingCalls.contains(callName))
    {
        d_ptr->m_waittingCalls[callName] = args;
        return;
    }
    if (d_ptr->m_processingCalls.contains(callName))
    {
        d_ptr->m_waittingCalls.insert(callName, args);
    } else {
        QDBusPendingCallWatcher *watcher = new QDBusPendingCallWatcher(asyncCallWithArgumentList(callName, args));
        connect(watcher, &QDBusPendingCallWatcher::finished, this, &__OrgDeepinDdeLoginedInterface::onPendingCallFinished);
        d_ptr->m_processingCalls.insert(callName, watcher);
    }
}

void __OrgDeepinDdeLoginedInterface::onPendingCallFinished(QDBusPendingCallWatcher *w)
{
    w->deleteLater();
    const auto callName = d_ptr->m_processingCalls.key(w);
    Q_ASSERT(!callName.isEmpty());
    if (callName.isEmpty())
        return;
    d_ptr->m_processingCalls.remove(callName);
    if (!d_ptr->m_waittingCalls.contains(callName))
        return;
    const auto args = d_ptr->m_waittingCalls.take(callName);
    CallQueued(callName, args);
}
