#!/bin/bash
display_daemon="/usr/lib/deepin-daemon/greeter-display-daemon"
if [ -x $display_daemon ]; then
    $display_daemon &
fi
export QT_QPA_PLATFORM=wayland

export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/aarch64-linux-gnu/

export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/plugins/platforms:/usr/plugins/platforms

export QT_PLUGIN_PATH=/usr/local/plugins:/usr/plugins

export QML2_IMPORT_PATH=/usr/local/qml:/usr/lib/aarch64-linux-gnu/qt5/qml

export XDG_DATA_DIRS=/usr/local/share:/usr/share

export XDG_CURRENT_DESKTOP=Deepin

export QT_DEBUG_PLUGINS=1


QT_SCALE_FACTOR=1.0 /usr/bin/lightdm-deepin-greeter -platformtheme deepin
