#!/bin/bash
display_daemon="/usr/lib/deepin-daemon/greeter-display-daemon"
if [ -x $display_daemon ]; then
    $display_daemon &
fi
export QT_QPA_PLATFORM=wayland

export LD_LIBRARY_PATH=/opt/usr/lib:/opt/usr/lib/aarch64-linux-gnu/

export QT_QPA_PLATFORM_PLUGIN_PATH=/opt/usr/plugins/platforms

export QT_PLUGIN_PATH=/opt/usr/plugins

export QML2_IMPORT_PATH=/opt/usr/qml:/usr/lib/aarch64-linux-gnu/qt5/qml

export XDG_DATA_DIRS=/opt/usr/share:/usr/share

/usr/bin/lightdm-deepin-greeter
