#!/bin/bash
export KWIN_COMPOSE=O2ES

export GDK_BACKEND=x11


export QT_QPA_PLATFORM=wayland

export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/aarch64-linux-gnu/

export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/plugins/platforms:/usr/local/lib/aarch64-linux-gnu/plugins/platforms

export QT_PLUGIN_PATH=/usr/local/plugins:/usr/local/lib/aarch64-linux-gnu/plugins/

export QML2_IMPORT_PATH=/usr/local/qml:/usr/local/lib/aarch64-linux-gnu/qml:/usr/lib/aarch64-linux-gnu/qt5/qml

export XDG_DATA_DIRS=/usr/local/share:/usr/share



/usr/local/bin/kwin_wayland --xwayland --drm --no-lockscreen /etc/deepin/greeters.d/lightdm-deepin-greeter
