#!/bin/bash
export KWIN_COMPOSE=O2ES

export GDK_BACKEND=x11


export QT_QPA_PLATFORM=wayland

export LD_LIBRARY_PATH=/opt/usr/lib:/opt/usr/lib/aarch64-linux-gnu/

export QT_QPA_PLATFORM_PLUGIN_PATH=/opt/usr/plugins/platforms:/opt/usr/lib/aarch64-linux-gnu/plugins/platforms

export QT_PLUGIN_PATH=/opt/usr/plugins:/opt/usr/lib/aarch64-linux-gnu/plugins/

export QML2_IMPORT_PATH=/opt/usr/qml:/opt/usr/lib/aarch64-linux-gnu/qml:/usr/lib/aarch64-linux-gnu/qt5/qml

export XDG_DATA_DIRS=/opt/usr/share:/usr/share



/opt/usr/bin/kwin_wayland --xwayland --drm --no-lockscreen /etc/deepin/greeters.d/lightdm-deepin-greeter
